title: 'Michael Fangman | Portfolio'
author:
  name: 'Michael Fangman'
  email: hello@michaelfangman.com
taxonomies:
  - category
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
