title: 'Michael Fangman | User Experience Designer'
default_lang: en
author:
  name: 'Michael Fangman'
  email: hello@michaelfangman.com
taxonomies:
  - category
metadata:
  description: ' UX & UI Designer living and working in Mpls'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
